// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNR2irOSrz-rGd08ephilOnxC5rs-Kgv0',
    appId: '1:964650950791:web:1621b18ab8be74e3e89822',
    messagingSenderId: '964650950791',
    projectId: 'proyectfire-443af',
    authDomain: 'proyectfire-443af.firebaseapp.com',
    storageBucket: 'proyectfire-443af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpDA9-tjP3VIgZjeFc11bUcMJYSf34bHQ',
    appId: '1:964650950791:android:353e7c952980c9c4e89822',
    messagingSenderId: '964650950791',
    projectId: 'proyectfire-443af',
    storageBucket: 'proyectfire-443af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-YAH0mPTIgTl-850HpRFaCM6YASx6-Gc',
    appId: '1:964650950791:ios:f641ae97639ea976e89822',
    messagingSenderId: '964650950791',
    projectId: 'proyectfire-443af',
    storageBucket: 'proyectfire-443af.firebasestorage.app',
    iosBundleId: 'com.example.proyectfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-YAH0mPTIgTl-850HpRFaCM6YASx6-Gc',
    appId: '1:964650950791:ios:f641ae97639ea976e89822',
    messagingSenderId: '964650950791',
    projectId: 'proyectfire-443af',
    storageBucket: 'proyectfire-443af.firebasestorage.app',
    iosBundleId: 'com.example.proyectfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNR2irOSrz-rGd08ephilOnxC5rs-Kgv0',
    appId: '1:964650950791:web:23ab8e02b79df8fce89822',
    messagingSenderId: '964650950791',
    projectId: 'proyectfire-443af',
    authDomain: 'proyectfire-443af.firebaseapp.com',
    storageBucket: 'proyectfire-443af.firebasestorage.app',
  );

}