// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArkWo5GVAVTGT4SY6_oIDMVQTSZHLvwKk',
    appId: '1:1047387401667:web:938f24940b1d57be7a2176',
    messagingSenderId: '1047387401667',
    projectId: 'proyectfire-443af',
    authDomain: 'proyectfire-443af.firebaseapp.com',
    storageBucket: 'proyectfire-443af.firebasestorage.app',
    measurementId: 'G-ZTBNC6954K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGonRmQq61i_TYya4kAmV7Wf46ZIEt660',
    appId: '1:1047387401667:android:15f815ea0737d1437a2176',
    messagingSenderId: '1047387401667',
    projectId: 'proyectfire-443af',
    storageBucket: 'proyectfire-443af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKoE_nNSyYUrLFFujiI-xW4gyysSytpCA',
    appId: '1:1047387401667:ios:dec902295d34d04e7a2176',
    messagingSenderId: '1047387401667',
    projectId: 'proyectfire-443af',
    storageBucket: 'proyectfire-443af.firebasestorage.app',
    iosBundleId: 'com.example.proyectfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKoE_nNSyYUrLFFujiI-xW4gyysSytpCA',
    appId: '1:1047387401667:ios:dec902295d34d04e7a2176',
    messagingSenderId: '1047387401667',
    projectId: 'proyectfire-443af',
    storageBucket: 'proyectfire-443af.firebasestorage.app',
    iosBundleId: 'com.example.proyectfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArkWo5GVAVTGT4SY6_oIDMVQTSZHLvwKk',
    appId: '1:1047387401667:web:a9c1b8b6d57aa04c7a2176',
    messagingSenderId: '1047387401667',
    projectId: 'proyectfire-443af',
    authDomain: 'proyectfire-443af.firebaseapp.com',
    storageBucket: 'proyectfire-443af.firebasestorage.app',
    measurementId: 'G-HBTVG71E4D',
  );
}
